[toolchain]
channel = "nightly-2025-01-18"
components = ["rust-src", "rustfmt", "clippy", "llvm-tools", "rust-analyzer", "rustc-codegen-cranelift-preview"]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
